# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: joaomart <joaomart@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/30 09:41:16 by joaomart          #+#    #+#              #
#    Updated: 2025/01/02 10:49:31 by joaomart         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
CFLAGS = -Wall -Wextra -Werror
CC = cc

#| Libft & ft_printf |#
LIBFT_DIR = libs/libft
LIBFT = $(LIBFT_DIR)/libft.a
FT_PRINTF_DIR = libs/ft_printf
FT_PRINTF = $(FT_PRINTF_DIR)/libftprintf.a
INCLUDES = -I . -I include -I $(LIBFT_DIR) -I $(FT_PRINTF_DIR)

#| Checker |#
CHECKER_DIR =

#| Sources |#
STACK_SRCS = 

SRCS =

OBJS =

fclean: clean


re: fclean all

.PHONY: all clean fclean re
