# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: joaomart <joaomart@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/12/30 09:41:16 by joaomart          #+#    #+#              #
#    Updated: 2024/12/30 13:08:51 by joaomart         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
FLAGS = -Wall -Wextra -Werror
CC = cc $(FLAGS)

LIBFT = libs/libft/libft.a
FT_PRINTF = libs/ft_printf/ft_printf.a

SRCS =

OBJS = 

.PHONY: all clean fclean re
